<<<<<<< HEAD
<<<<<<< Updated upstream
title: Byron Judah
logo: /assets/img/Modern_Avatar_NoBanner.png
description: My Personal Website
show_downloads: true
theme: jekyll-theme-minimal
=======
=======
>>>>>>> 8a8cd85f0f684c6c5c320f3330daa2ea3df076c2
#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
<<<<<<< HEAD
name: Byron Judah

# Short bio or description (displayed in the header)
description: Test Stuff

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/60358337?s=460&v=4
=======
name: Your Name

# Short bio or description (displayed in the header)
description: Web Developer from Somewhere

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
>>>>>>> 8a8cd85f0f684c6c5c320f3330daa2ea3df076c2

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
<<<<<<< HEAD
  email: byron.judah@gmail.com
  facebook:
  flickr:
  github: patronorion
=======
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
>>>>>>> 8a8cd85f0f684c6c5c320f3330daa2ea3df076c2
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
<<<<<<< HEAD
  twitter: 
=======
  twitter: jekyllrb
>>>>>>> 8a8cd85f0f684c6c5c320f3330daa2ea3df076c2
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
<<<<<<< HEAD
url: https://patronorion.github.io
=======
url:
>>>>>>> 8a8cd85f0f684c6c5c320f3330daa2ea3df076c2

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
<<<<<<< HEAD
>>>>>>> Stashed changes
=======
>>>>>>> 8a8cd85f0f684c6c5c320f3330daa2ea3df076c2
